### PR TITLE
Update Nginx Proxy Manager to 2.9.19

### LINKED ISSUE #269: Update to 2.9.19
Hi,

As far as I can tell, this is still using 2.9.18. Can it please be updated to 2.9.19?

Thanks.

### PR DESCRIPTION
**Pull request by MrTyton**
Resolves #269

### CODE REVIEW

**Comment by cmccallu** [comment]
Thanks for updating the version mate! Not sure why updates have stopped for 6+ months even for a simple version bump!

**Comment by alfonder** [comment]
Yes, a bad situation. I'm forced to switch to the bulky jc21's release.

**Comment by Leolele99** [comment]
Any updates?

**Comment by jlesage** [comment]
The latest image now integrates this.
A huge amount of work has been done on the baseimage, it's for this reason it took so much time (even if the NPM update itself was small).

**Comment by cmccallu** [comment]
Appreciate all your hard work on this! Leave me in a tuff spot tho as I have migrated over to the jc21 container on the weekend...

**Pull request closed without merging**
